### ISSUE TITLE
P2 Solution Template Regression Test Suite

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#27] opened 2020-08-05 09:08 UTC
The Solution Template is fully regression tested in the build pipeline. (Previously it was going to be in preview which presumed that Microsoft will have checked the submission thoroughly by the. But they don't. They only do that when choose to go LIVE! Actually getting to preview seems to just require that the ARM TTK tests pass, which we already know is the case. Better to test it automatically in the build pipeline rather than have an extra manual step in Preview. Now, once its ready to submit for preview there are no further tests to be performed. From then on its just about Microsoft validation)

(Note: tables are edited in [this ](https://docs.google.com/document/d/1wcWsssDRp6wCH0xJu-rQ0w_4asgLkS0E-J8IAZdX8Ho/edit?usp=sharing) Google Docs document. And permission needs to be provided to edit it)

- Each run of the template must be created in its own resource group with a unique name. Possibly the names of the tests below will work?
- If the resource group exists already it must be deleted.
- If the test succeeds, the resource group is deleted
- If the test fails, the resource group is retained for diagnostic purposes.
- The resource group must be tagged `Usage=test-temp`. These resource groups will be deleted at the COB IST. If they need to be retained overnight then the tag `ShutdownPolicy=excluded` must be added manually.

The tests are as follows

- Template Settings must be the default unless specified in the table below.

Test | SQLAZURE1 | SQLAZURE2 | SQLAZURE3 | SQLAZURE4 | SQLAZURE5 | SQLAZURE6
-- | -- | -- | -- | -- | -- | --
AG Tier | Standard | Standard | Standard | WAF | WAF | WAF
AG SKU | Standard_Small | Standard_Medium | Standard_Large | WAF_Medium | WAF_Large | WAF_Large
DB New | New | New | New | New | New | New
DB Type | SQLAZURE | SQLAZURE | SQLAZURE | SQLAZURE | SQLAZURE | SQLAZURE
Edition | Basic | Standard | Standard | Standard | Premium | Premium
RSO Name | Basic | S0 | S4 | S12 | P1 | P11
Image Offer | lansa-scalable-license | lansa-scalable-license | lansa-scalable-license | lansa-scalable-license | lansa-scalable-license | lansa-scalable-license
Image Plan | lansa-scalable-license-14-2 | w19d-14-2 | w16d-14-2 | w19d-15-0 | w16d-15-0 | w12r2d-15-0
Result | Success | Success | Success | Success | Success | Success

The tests for MYSQL and MSSQLS must programmatically create the database in the resource group before deploying the template.

Test | MYSQL1 | MSSQLS1
-- | -- | --
AG Tier | Standard | Standard
AG SKU | Standard_Medium | Standard_Medium
DB New | Existing | Existing
DB Type | MYSQL | MSSQLS
Edition | Standard | Standard
RSO Name | S2 | S2
Image Offer | lansa-scalable-license | lansa-scalable-license
Image Plan | lansa-scalable-license-14-2 | lansa-scalable-license-14-2
Result | Success | Success

**Comment by robe070** [comment] 2020-08-06 00:29
@VarunChopraAccolite @ashutosh-kumar1 FYI

**Comment by ashutosh-kumar1** [comment] 2020-08-19 17:55
@robe070, I need some clarity on the database test section of this issue.
As per the test, I was wondering how to create a database of type MYSQL and MSSQLS. 

I googled out and could find the below link which seems to create a MYSQL database: 
https://docs.microsoft.com/en-us/azure/mysql/quickstart-create-mysql-server-database-using-azure-powershell
But I couldn't proceed with it as I was unable to execute the command mentioned in the pre-requisite section.

I also checked in the database section in the azure portal and found that the subscription is not registered for using the resource provider 'Microsoft.DBforMySQL'
![MYSQL server creation error](https://user-images.githubusercontent.com/67790012/90672505-d623ac80-e273-11ea-9f8b-4d2f6e4378a8.PNG)

I created a database using the cmdlet 'New-AzSqlDatabase' but I think it creates a database of type 'SQLAZURE'.
Can you please help me on this and clarify if my understanding is correct.

**Comment by robe070** [comment] 2020-08-20 04:03
Here are the instructions on how to create a SQL Server server in the portal.
https://docs.microsoft.com/en-au/azure/azure-sql/virtual-machines/windows/create-sql-vm-portal

There is also a PowerShell method provided.

I think a template may be the best option. I've added sqlServerTemplate.json to the template repo. I created this from using the Portal option and then saving the resultant template. Its not parameterised and would probably require that. Maybe hard coding would be OK.

**Comment by robe070** [comment] 2020-08-20 04:07
For MySQL, Azure provides a template:
https://docs.microsoft.com/en-us/azure/mysql/quickstart-create-mysql-server-database-using-arm-template?tabs=azure-portal

**Comment by ashutosh-kumar1** [comment] 2020-08-20 04:18
@robe070, I can see the instruction https://docs.microsoft.com/en-au/azure/azure-sql/virtual-machines/windows/create-sql-vm-portal creates a VM with SQL server rather than a database.
Yesterday, I also went through the other link you mentioned: https://docs.microsoft.com/en-us/azure/mysql/quickstart-create-mysql-server-database-using-arm-template?tabs=azure-portal. The issue here again is the one that I had described above
```
{
            "apiVersion": "2017-12-01",
            "type": "Microsoft.DBforMySQL/servers",
            "location": "[parameters('location')]",
```
The type is not registered for our subscription.

**Comment by robe070** [comment] 2020-08-20 05:11
If you instantiate a MySQL instance through the portal then it throws a permissions error. I'm working through fixing that.

I expect SQL Server is the same. I'll also ensure that you can create a SQL Server database

**Comment by robe070** [comment] 2020-08-20 06:09
So you can now create an Azure Database for MySQL and an Azure SQL Server Virtual Machine.

**Comment by robe070** [comment] 2020-08-20 06:17
MySQL
![image](https://user-images.githubusercontent.com/4089160/90723721-9ce54e00-e300-11ea-9a0a-a4472002d122.png)

**Comment by ashutosh-kumar1** [comment] 2020-08-20 06:25
@robe070, Thanks for fixing the permission issue on priority. I will try creating a MYSQL database and test the template as required.
Can you share some information regarding the MSSQLS database type?

**Comment by robe070** [comment] 2020-08-20 06:26
MSSQLS (Azure SQL Server Virtual Machine) is also working as per my previous post above.

**Comment by ashutosh-kumar1** [comment] 2020-08-20 06:27
Thanks 👍

**Comment by robe070** [comment] 2020-08-20 06:35
@ashutosh-kumar1 
MySQL needs the database to be manually created. Follow this: https://docs.microsoft.com/en-us/azure/mysql/quickstart-create-mysql-server-database-using-azure-portal

I suggest you use the powershell cmdlet to run a script on the MySQL server. Its a linux VM and it should have PowerShell installed so you can use
```
Invoke-AzVMRunCommand -ResourceGroupName $VmResourceGroup -Name $VMname -CommandId 'RunPowerShellScript'
```

If that does not work, then you may use `RunShellScript` instead of `RunPowerShellScript`.

Info here: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/run-command

All you need to do in the script is the following:
```
rob@Azure:~$ mysql --host=rob-mysql.mysql.database.azure.com --user=lansa@rob-mysql -p
mysql> CREATE DATABASE lansa;
```

**Comment by robe070** [comment] 2020-08-20 06:37
MySQL
Note: that the connection security option to allow access to all Azure Services should be a change made in the template. Template to be stored in `lansa/azure-quickstart-templates` repo.

And when changing it in the portal its already taken 25 minutes and has not completed yet!

**Comment by robe070** [comment] 2020-08-20 06:44
SQL Server
Note that the deployment will automatically create a database if it does not already exist. 

I have successfully deployed to my SQL Server Virtual Machine.

**Comment by robe070** [comment] 2020-08-20 07:49
@ashutosh-kumar1 
The manual MySQL Deployment and url test has been successful

**Comment by ashutosh-kumar1** [comment] 2020-08-23 19:16
Hi @robe070,
I have modified the template file that you had added to enable it to pass the arm-ttk test cases.

I have also created a template to create MYSQL server, as well as database from a single template. No additional step needs to be performed. Moreover I have taken care to set allow connection to azure services to 'yes' for the server created (Refer resource group: mysql1Test). Also tested it by deploying the template using this database (Refer resource group: rgak).
I have created a pull request for the same: https://github.com/lansa/azure-quickstart-templates/pull/8 
Please verify the changes and provide review comments.

I am yet to test for MSSQL database. Will proceed with it today.

**Comment by robe070** [comment] 2020-08-24 05:28
@ashutosh-kumar1 MySQL deployment looks correct. I'll presume you need to rebase the PR before merging.

**Comment by robe070** [comment] 2020-08-24 05:29
I'm deploying MSSQLS and expect it to complete at about 4 pm AEST

**Comment by VarunChopraAccolite** [comment] 2020-08-24 05:36
hi @robe070 
Regarding the below point, we generate the Resource Group appended with the Build Number, to retain the fail build. Below change won't be required in that case. Let me know your inputs on this one.

- If the resource group exists already it must be deleted.

**Comment by robe070** [comment] 2020-08-24 05:50
@VarunChopraAccolite So the resource group is unique for each build and thus should never exist? And if it does, then its not owned/created by the pipeline and thus should not be deleted.

Agreed.

**Comment by robe070** [comment] 2020-08-24 06:17
@ashutosh-kumar1 
> I'm deploying MSSQLS and expect it to complete at about 4 pm AEST

There was an error in a parameter. Now fixed and redeploying. ETA 4:45 AEST

**Comment by VarunChopraAccolite** [comment] 2020-08-24 06:18
> @VarunChopraAccolite So the resource group is unique for each build and thus should never exist? And if it does, then its not owned/created by the pipeline and thus should not be deleted.
> 
> Agreed.

yes @robe070 in case of success scenarios it will delete the Resource Group, the Resource Group will be available for review in case of failure mode where the deletion based on tagging will come into place.

**Comment by robe070** [comment] 2020-08-24 06:58
@ashutosh-kumar1 
My MSSQLS test has succeeded...

Attached parameters file for the sqlServerTemplate.json. (Extension `.txt` so that github accepts it)
[parameters.json](https://github.com/robe070/cookbooks/files/5116240/parameters.txt)

Also the sqlServerTemplate.json file I used, which should be identical to the one that you've fixed.
[sqlServerTemplate.json](https://github.com/robe070/cookbooks/files/5116249/template.txt)

**Comment by ashutosh-kumar1** [comment] 2020-08-24 08:18
Thanks a lot @robe070.

**Comment by ashutosh-kumar1** [comment] 2020-08-24 20:39
Hi @robe070,
I was unable to output the public IP address at the time of MSSQLS deployment. This is probably because the IP allocated is dynamic and is available in resources.azure.com but not available at the time of deployment.
Please find below the screenshot available in resources.azure.com
![public ip details](https://user-images.githubusercontent.com/67790012/91093282-dad2d100-e676-11ea-8239-c156b158fa9a.PNG)
Also find the output received on accessing this property post deployment:
pip              Object                     {
  "provisioningState": "Succeeded",
  "resourceGuid": "8b2ff8cf-62d6-40a5-bfc8-3abe30fe400c",
  "publicIPAddressVersion": "IPv4",
  "publicIPAllocationMethod": "Dynamic",
  "idleTimeoutInMinutes": 4,
  "ipTags": []
}
This object does not contain the ipAddress field at the deployment stage.
We can anyways get the IP post-deployment using PowerShell cmdlet: 
`Get-AzPublicIpAddress -Name <publicIPAddressName> -ResourceGroupName <resourceGroupName>`
for which I will display the publicIPAddressName field in the output.

Please provide your thoughts on this.

**Comment by robe070** [comment] 2020-08-24 23:58
@ashutosh-kumar1 
Yes, use the cmdlet post-deployment.

**Comment by ashutosh-kumar1** [comment] 2020-08-25 13:24
Hi @robe070,
I have added a commit to feature/azure-images branch of cookbooks repo to create the SQL databases. Please review: https://github.com/robe070/cookbooks/commit/ad0f7fac38bd4f5e86e7b442a9c046129d9d4db5
It will accept MYSQL or MSSQLS as input params and create the database using the lansa\azure-quickstart-templates repo.

Please merge the pull request: https://github.com/lansa/azure-quickstart-templates/pull/10, so that I can proceed to add this in the pipeline.

**Comment by VarunChopraAccolite** [comment] 2020-08-26 05:07
hi @robe070 
Please update the combination test SQLAZURE6 for column 6 to use a different combination than WAF_v2.
CC: @knagasekharreddy 
Thanks

**Comment by robe070** [comment] 2020-08-26 06:52
@VarunChopraAccolite 
SQLAZURE6 WAV_V2 test case altered in table in first comment above.

**Comment by VarunChopraAccolite** [comment] 2020-08-30 02:30
hi @robe070 
The Template Regression Tests are up and running in the Template release pipeline. Also, the changes are in place across the pipelines to tag the resource group `Usage=test-temp` and delete on the successful run.

![image](https://user-images.githubusercontent.com/24430923/91649942-c9366280-ea96-11ea-99e0-fb54a3c0c0bb.png)

Thanks

**Closed as completed** 2020-08-31 03:38 UTC
Labels: enhancement, test, azure
